---
dataplane:
  image:
    tag: latest
    pullPolicy: IfNotPresent
  edc:
    endpoints:
      default:
        port: 8080
        path: /consumer/dataplane/api
      public:
        port: 8185
        path: /consumer/dataplane/api/public
      control:
        port: 9999
        path: /consumer/dataplane/api/control
      metrics:
        port: 9090
        path: /consumer/dataplane/metrics
  ingresses:
    - enabled: true
      hostname: "materialpass.int.demo.catena-x.net"
      endpoints:
        - default
        - public
        - control
        - metrics
      className: "nginx"
      # -- Enables TLS on the ingress resource
      tls: false
  opentelemetry:
    properties: |-
      otel.javaagent.enabled=false
      otel.javaagent.debug=false
  env:
    EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT: "http://materialpass-edc-controlplane:8182/consumer/controlplane/validation"
    EDC_VAULT_HASHICORP_URL: https://vault.demo.catena-x.net
    EDC_VAULT_HASHICORP_API_SECRET_PATH: /v1/material-pass
    EDC_VAULT_HASHICORP_TOKEN: s.I7Hxwn25D9YpzFgbC8WEKAa5
    EDC_OAUTH_TOKEN_URL: https://daps1.int.demo.catena-x.net/token
    EDC_OAUTH_PROVIDER_JWKS_URL: https://daps1.int.demo.catena-x.net/.well-known/jwks.json 
    EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL
    EDC_VAULT_HASHICORP_HEALTH_CHECK_STANDBY_OK: "true"

controlplane:
  enabled: true
  image:
    tag: latest # 0.1.0
    pullPolicy: IfNotPresent
  edc:
    endpoints:
      default:
        port: 8080
        path: /consumer/controlplane/api
      data:
        port: 8181
        path: /consumer/controlplane/data
      validation:
        port: 8182
        path: /consumer/controlplane/validation
      control:
        port: 9999
        path: /consumer/controlplane/api/control
      ids:
        port: 8282
        path: /consumer/api/v1/ids
      metrics:
        port: 9090
        path: /consumer/controlplane/metrics
  ingresses:
    - enabled: true
      hostname: "materialpass.int.demo.catena-x.net"
      endpoints:
      - default
      - data
      - validation
      - control
      - ids
      - metrics
      className: "nginx"
      tls: false
  opentelemetry:
    properties: |-
      otel.javaagent.enabled=false
      otel.javaagent.debug=false
  env:
    EDC_OAUTH_CLIENT_ID: 0D:1D:9E:E2:1C:B1:E1:61:21:40:86:02:38:FB:0A:37:18:F8:04:4E:keyid:0D:1D:9E:E2:1C:B1:E1:61:21:40:86:02:38:FB:0A:37:18:F8:04:4E
    EDC_OAUTH_PRIVATE_KEY_ALIAS: ids-daps_key
    EDC_OAUTH_PUBLIC_KEY_ALIAS: ids-daps_crt
    IDS_WEBHOOK_ADDRESS: "http://materialpass.int.demo.catena-x.net/consumer/api/v1/ids"
    EDC_IDS_ENDPOINT: "http://materialpass.int.demo.catena-x.net/consumer/api/v1/ids"
    EDC_IDS_DESCRIPTION: "sokrates EDC Control Plane"
    EDC_DATASOURCE_ASSET_URL: &psqlJdbcUrl "jdbc:postgresql://postgresql:5432/edc"
    EDC_DATASOURCE_CONTRACTDEFINITION_URL: *psqlJdbcUrl
    EDC_DATASOURCE_CONTRACTNEGOTIATION_URL: *psqlJdbcUrl
    EDC_DATASOURCE_POLICY_URL: *psqlJdbcUrl
    EDC_DATASOURCE_TRANSFERPROCESS_URL: *psqlJdbcUrl
    EDC_DATAPLANE_SELECTOR_HTTPPROXY_URL: http://materialpass-edc-dataplane:9999/consumer/dataplane/api/control
    EDC_DATAPLANE_SELECTOR_HTTPPROXY_PROPERTIES: >-
      {
        "publicApiUrl": "https://materialpass.int.demo.catena-x.net/consumer/dataplane/api/public"
      }
    EDC_TRANSFER_PROXY_ENDPOINT: http://materialpass-edc-dataplane:8185/consumer/dataplane/api/public
    EDC_TRANSFER_PROXY_TOKEN_SIGNER_PRIVATEKEY_ALIAS: ids-daps_key
    EDC_TRANSFER_PROXY_TOKEN_VERIFIER_PUBLICKEY_ALIAS: ids-daps_crt
    EDC_VAULT_HASHICORP_URL: https://vault.demo.catena-x.net
    EDC_VAULT_HASHICORP_API_SECRET_PATH: /v1/material-pass
    EDC_VAULT_HASHICORP_TOKEN: s.I7Hxwn25D9YpzFgbC8WEKAa5
    EDC_OAUTH_TOKEN_URL: https://daps1.int.demo.catena-x.net/token
    EDC_OAUTH_PROVIDER_JWKS_URL: https://daps1.int.demo.catena-x.net/.well-known/jwks.json 
    EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL
    EDC_VAULT_HASHICORP_HEALTH_CHECK_STANDBY_OK: "true"
    EDC_DATA_ENCRYPTION_ALGORITHM: NONE
    EDC_DATA_ENCRYPTION_KEYS_ALIAS: edc-encryption-key
    EDC_API_AUTH_KEY: password
