logLevel: 7
logDir: "log"
logBaseFileName: "material-pass.log"
maxRetries: 3

keycloak:
  tokenUri: 'https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token'
  #tokenUri: 'http://localhost:8088/auth/realms/CX-Central/protocol/openid-connect/token'

variables:
  serverUrl: 'https://materialpass.int.demo.catena-x.net'
  providerUrl: 'https://materialpass.int.demo.catena-x.net/provider/api/v1/ids/data'
  registryUrl: 'https://semantics.int.demo.catena-x.net'
  apiKey: 'password'


vault:
  #uri: 'https://vault.demo.catena-x.net'
  uri: 'http://localhost:8200'
  token-file: 'vault.token.yml'
