---

# When deploying an EDC, there are various configuration parameters that should not be part of the configuration file.
# To not serve a bad example, this demo will set some settings using secrets as well. In a productive environment this secrets would probably be deployed independently.


{{- $provider_psql_password := .Values.providerpostgres.auth.password -}}
{{- $api_auth_key := "password" -}}
{{- $vault_token := .Values.dataplane.env.EDC_VAULT_HASHICORP_TOKEN -}}

---

apiVersion: v1
kind: Secret
metadata:
  name: provider-control-secret
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "edc-provider.labels" . | nindent 4 }}
type: Opaque
stringData:
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/api/auth-tokenbased
  EDC_API_AUTH_KEY: {{ $api_auth_key | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/asset-index-sql
  EDC_DATASOURCE_ASSET_PASSWORD: {{ $provider_psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/contract-definition-store-sql
  EDC_DATASOURCE_CONTRACTDEFINITION_PASSWORD: {{ $provider_psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/contract-negotiation-store-sql
  EDC_DATASOURCE_CONTRACTNEGOTIATION_PASSWORD: {{ $provider_psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/policy-store-sql
  EDC_DATASOURCE_POLICY_PASSWORD: {{ $provider_psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/transfer-process-store-sql
  EDC_DATASOURCE_TRANSFERPROCESS_PASSWORD: {{ $provider_psql_password | toString | quote }}
  # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/hashicorp-vault
  EDC_VAULT_HASHICORP_TOKEN: {{ $vault_token | toString | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: provider-data-secret
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "edc-provider.labels" . | nindent 4 }}
type: Opaque
stringData:
  # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/hashicorp-vault
  EDC_VAULT_HASHICORP_TOKEN: {{ $vault_token | toString | quote }}


