#################################################################################
# Catena-X - Product Passport Consumer Application
#
# Copyright (c) 2022, 2023 BASF SE, BMW AG, Henkel AG & Co. KGaA
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

### The fully configuration is available in https://github.com/eclipse-tractusx/tractusx-edc/tree/main/charts/tractusx-connector


---


tractusx-connector:
  participant:
    id: &bpnNumber "<path:material-pass/data/beta/edc/participant#bpnNumber>"

  controlplane:
    enabled: true
    endpoints:
      # -- default api for health checks, should not be added to any ingress
      default:
        # -- port for incoming api calls
        port: 8080
        # -- path for incoming api calls
        path: /BPNL000000000000/api
      # -- data management api, used by internal users, can be added to an ingress and must not be internet facing
      management:
        # -- port for incoming api calls
        port: 8081
        # -- path for incoming api calls
        path: /BPNL000000000000/management
        # -- authentication key, must be attached to each 'X-Api-Key' request header
        authKey: <path:material-pass/data/beta/edc/oauth#api.key>
      # -- control api, used for internal control calls. can be added to the internal ingress, but should probably not
      control:
        # -- port for incoming api calls
        port: 8083
        # -- path for incoming api calls
        path: /BPNL000000000000/control
      # -- ids api, used for inter connector communication and must be internet facing
      protocol:
        # -- port for incoming api calls
        port: 8084
        # -- path for incoming api calls
        path: /BPNL000000000000/api/v1/dsp
      # -- metrics api, used for application metrics, must not be internet facing
      metrics:
        # -- port for incoming api calls
        port: 9090
        # -- path for incoming api calls
        path: /BPNL000000000000/metrics
      # -- observability api with unsecured access, must not be internet facing
      observability:
        # -- port for incoming API calls
        port: 8085
        # -- observability api, provides /health /readiness and /liveness endpoints
        path: /BPNL000000000000/observability
        # -- allow or disallow insecure access, i.e. access without authentication
        insecure: true

    ## Ingress declaration to expose the network service.
    ingresses:
      ## Public / Internet facing Ingress
      - enabled: true
        # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
        hostname: "materialpass.beta.demo.catena-x.net"
  dataplane:
    enabled: true
    endpoints:
      default:
        port: 8080
        path: /BPNL000000000000/api
      public:
        port: 8081
        path: /BPNL000000000000/api/public
      control:
        port: 8083
        path: /BPNL000000000000/api/dataplane/control
      proxy:
        port: 8186
        path: /BPNL000000000000/proxy
      observability:
        # -- port for incoming API calls
        port: 8085
        # -- observability api, provides /health /readiness and /liveness endpoints
        path: /BPNL000000000000/observability
        # -- allow or disallow insecure access, i.e. access without authentication
        insecure: true
      metrics:
        port: 9090
        path: /BPNL000000000000/metrics
    ## Ingress declaration to expose the network service.
    ingresses:
      ## Public / Internet facing Ingress
      - enabled: true
        # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
        hostname: "materialpass.beta.demo.catena-x.net"
        # -- Additional ingress annotations to add
       
  postgresql:
    username: <path:material-pass/data/beta/edc/database#user>
    password: <path:material-pass/data/beta/edc/database#user>
    auth:
      username: <path:material-pass/data/beta/edc/database#user>
      password: <path:material-pass/data/beta/edc/database#user>

  vault:
    fullnameOverride: "vault"
    hashicorp:
      url: <path:material-pass/data/beta/edc/vault#vault.hashicorp.url>
      token: <path:material-pass/data/beta/edc/vault#vault.hashicorp.token>
      paths:
        secret: <path:material-pass/data/beta/edc/vault#vault.hashicorp.api.secret.path>
        health: /v1/sys/health
    secretNames:
      transferProxyTokenSignerPrivateKey: ids-daps_key
      transferProxyTokenSignerPublicKey: ids-daps_crt
      transferProxyTokenEncryptionAesKey: edc-encryption-key
      dapsPrivateKey: ids-daps_key
      dapsPublicKey: ids-daps_crt

  daps:
    url: "https://daps.beta.demo.catena-x.net"
    clientId: <path:material-pass/data/beta/edc/oauth#client.id>
    connectors:
      - id: <path:material-pass/data/beta/edc/oauth#client.id>
        name: edcconector
        attributes:
          referringConnector: "https://materialpass.beta.demo.catena-x.net/consumer/<path:material-pass/data/beta/edc/participant#bpnNumber>"
        certificate: <path:material-pass/data/ids-daps_crt#content>

  backendService:
    httpProxyTokenReceiverUrl: "https://materialpass.beta.demo.catena-x.net/endpoint"
    
  idsdaps:
    connectors:
      - certificate: <path:material-pass/data/ids-daps_crt#content>

postgresql:
  auth:
    username: <path:material-pass/data/beta/edc/database#user>
    password: <path:material-pass/data/beta/edc/database#password>