#################################################################################
# Catena-X - Product Passport Consumer Application
#
# Copyright (c) 2022, 2023 BASF SE, BMW AG, Henkel AG & Co. KGaA
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

frontend:
  ingress:
    enabled: true
    #className: ""
    annotations:
      ingressClassName: nginx
      # kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: materialpass.int.demo.catena-x.net
        paths:
          - path: /passport(/|$)(.*)
            pathType: Prefix
    tls:
      - secretName: tls-secret
        hosts:
          - materialpass.int.demo.catena-x.net

  edc:
    clientId: <path:material-pass/data/int/aasregistry#client.id>
    clientSecret: <path:material-pass/data/int/aasregistry#client.secret>
    xApiKey: <path:material-pass/data/int/edc/oauth#api.key>

  productpass:
    backend_url: "materialpass.int.demo.catena-x.net"
    idp_url: "centralidp.int.demo.catena-x.net/auth/"
    keycloak:
      clientId: "Cl13-CX-Battery"
      realm: "CX-Central"
      onLoad: "login-required"
    irsDelay: ""
    irsMaxWaitingTime: ""

backend:
  ingress:
    enabled: true
    # className: "nginx"
    annotations:
      ingressClassName: nginx
      # kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: &hostname "materialpass.int.demo.catena-x.net"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: tls-secret
        hosts:
          - *hostname
  edc:
    xApiKey: <path:material-pass/data/int/edc/oauth#api.key>
    participantId:  <path:material-pass/data/int/edc/participant#bpnNumber>
    endpoint: "https://materialpass.int.demo.catena-x.net/consumer"
    management: "/management/v2"
    catalog: "/catalog/request"
    negotiation: "/contractnegotiations"
    transfer: "/transferprocesses"
    delay: 100
  oauth:
    clientId: <path:material-pass/data/int/backend#clientId>
    clientSecret: <path:material-pass/data/int/backend#clientSecret>
    realm: CX-Central
    resource: Cl13-CX-Battery
    tokenUri: "https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
    userInfoUri: "https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/userinfo"

  url: *hostname
  serverPort: 8888
  logging:
    level:
      root: INFO
      utils: INFO
  maxRetries: 10
  securityCheck:
    enabled: true
    bpn: true
    edc: true
  irs:
    endpoint: "materialpass-irs.int.demo.catena-x.net"
  process:
    authorizationKey: "<path:material-pass/data/int/backend/#signKey>"
  passport:
    aspects:
      - "urn:bamm:io.catenax.generic.digital_product_passport:1.0.0#DigitalProductPassport"
      - "urn:bamm:io.catenax.battery.battery_pass:3.0.1#BatteryPass"
      - "urn:bamm:io.catenax.transmission.transmission_pass:1.0.0#TransmissionPass"
  digitalTwinRegistry:
    url: "https://semantics.int.demo.catena-x.net/registry"
    endpoints:
      search: "/lookup/shells"
      digitalTwin: "/shell-descriptors"
      subModel: "/submodel-descriptors"
    timeouts:
      search: 10
      negotiation: 40
      transfer: 10
      digitalTwin: 20
    temporaryStorage:
      enabled: true
    discoveryFinderUrl: "https://semantics.int.demo.catena-x.net/discoveryfinder/api/v1.0/administration/connectors/discovery/search"
    bpnKey: "manufacturerPartId"
    bpnSearchUrl: "/api/v1.0/administration/connectors/bpnDiscovery/search"
    edcKey: "bpn"