#################################################################################
# Catena-X - Product Passport Consumer Application
#
# Copyright (c) 2022, 2023 BASF SE, BMW AG, Henkel AG & Co. KGaA
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

# Default values for dpp-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: "digital-product-pass"
replicaCount: 1
namespace: product-material-pass

frontend:
  name: "dpp-frontend"
  image:
    repository: docker.io/tractusx/digital-product-pass-frontend
    pullPolicy: Always
  # -- Existing image pull secret to use to [obtain the container image from private registries](https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry)
  imagePullSecrets: []

  service:
    # -- [Service type](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types) to expose the running application on a set of Pods as a network service
    type: ClusterIP
    port: 8080

  # -- ingress declaration to expose the dpp-frontend service
  ingress:
    enabled: false
    hosts: []

  # -- product passport UI configuration
  productpass:
    # -- url of the digital product pass backend service
    backend_url: ""
    # -- url of the identity provider service
    idp_url: ""
    # -- required: digital product passport version number - default value: v3.0.1
    passport:
      version: "v3.0.1"    ## Mandatory Field, passport version must be available (Semantic Structure)
    api:
      # -- max retries for getting status
      max_retries: 20
      # -- default timeout  - 45 seconds in milliseconds
      timeout: 60000
      # -- delay from getting status
      delay: 1000
    # -- keycloak specific configuration for frontend authentication 
    keycloak:
      clientId: ""
      realm: ""
      onLoad: "login-required"

backend:
  name: "dpp-backend"
  image:
    repository: docker.io/tractusx/digital-product-pass-backend
    pullPolicy: Always
  # -- Existing image pull secret to use to [obtain the container image from private registries](https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry)
  imagePullSecrets: []

  service:
  # -- [Service type](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types) to expose the running application on a set of Pods as a network service
    type: ClusterIP
    port: 8888


  # -- ingress declaration to expose the dpp-backend service
  ingress:
    enabled: false

  avp:
    helm:
      # -- registry specific credentials 
      clientId: "<Add client id here>"
      clientSecret: "<Add client secret here>"
      # -- API Key from EDC
      xApiKey: "<Add API key here>"
      # -- BPN Number
      participantId: "<Add participant id here>"

  # -- backend sepcific configuration
  application:
    yml: |-
      spring:
        name: "Catena-X Product Passport Consumer Backend"
        main:
          allow-bean-definition-overriding: true
        devtools:
          add-properties: false
        jackson:
          serialization:
            indent_output: true

      logging:
        level:
          root: INFO
          utils: INFO

      configuration:
        maxRetries: 5

        keycloak:
          realm: <test-realm>
          resource: <test-resource>
          tokenUri: "https://<test-keycloak-url>/auth/realms/<test-realm>/protocol/openid-connect/token"
          userInfoUri: "https://<test-keycloak-url>/auth/realms/<test-realm>/protocol/openid-connect/userinfo"

        edc:
          endpoint: "https://<digital-product-pass-url>/consumer"
          management: "/management/v2"
          catalog: "/catalog/request"
          negotiation: "/contractnegotiations"
          transfer: "/transferprocesses"
          receiverEndpoint: "https://<digital-product-pass-url>/endpoint"

        process:
          store: true
          dir: "process"
          indent: true
          signKey: ""

        endpoints:
          registryUrl: "https://<digital-twin-registry-url>"

        passport:
          dataTransfer:
            encrypt: true
            indent: true
            dir: "data/transfer"
          versions:
            - "v3.0.1"
        
        vault:
          type: "local"
          file: "vault.token.yml"
          pathSep: "."
          prettyPrint: true
          indent: 2
          defaultValue: "<Add secret value here>"
          attributes:
            - "client.id"
            - "client.secret"
            - "edc.apiKey"
            - "edc.participantId"

      server:
        error:
          include-message: ALWAYS
          include-binding-errors: ALWAYS
          include-stacktrace: ON_PARAM
          include-exception: false
        port: 8888
        tomcat:
          max-connections: 10000

# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-resource-requests-and-limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 512Mi

# [node selector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) to constrain pods to nodes
nodeSelector: {}

# [tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) to configure preferred nodes
tolerations: []

# [affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) to configure which nodes the pods can be scheduled on
affinity: {}
