apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "consumer-ui.fullname" . }}
  labels:
    {{- include "consumer-ui.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "consumer-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "consumer-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:          
            - name: "VUE_APP_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key:  clientId
                  name: avp-cx-registry-auth
            - name: "VUE_APP_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  key:  clientSecret
                  name: avp-cx-registry-auth
            - name: "X_API_KEY"
              valueFrom:
                secretKeyRef:
                  key:  xApiKey
                  name: avp-edc-oauth
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
