apiVersion: v1
kind: Secret
metadata:
  name: avp-cx-registry-auth
  labels:
    {{- include "consumer-ui.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  clientId: {{ .Values.avp.helm.clientId }}
  clientSecret: {{ .Values.avp.helm.clientSecret }}
---
