apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "consumer-backend.fullname" . }}
  labels:
    {{- include "consumer-backend.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "consumer-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "consumer-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:          
            - name: "client.id"
              valueFrom:
                secretKeyRef:
                  key:  clientId
                  name: avp-cx-registry-auth
            - name: "client.secret"
              valueFrom:
                secretKeyRef:
                  key:  clientSecret
                  name: avp-cx-registry-auth
            - name: "apiKey"
              valueFrom:
                secretKeyRef:
                  key:  xApiKey
                  name: avp-edc-oauth
          ports:
            - containerPort: 8888
              name: http
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
